discussion_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Discussion:index" }
    methods:  GET

discussion_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Discussion:show" }
    methods:  GET

discussion_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Discussion:new" }
    methods:  [GET, POST]

discussion_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Discussion:edit" }
    methods:  [GET, POST]

discussion_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Discussion:delete" }
    methods:  DELETE
