matchs_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Matchs:index" }
    methods:  GET

matchs_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Matchs:show" }
    methods:  GET

matchs_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Matchs:new" }
    methods:  [GET, POST]

matchs_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Matchs:edit" }
    methods:  [GET, POST]

matchs_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Matchs:delete" }
    methods:  DELETE
