participe_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Participe:index" }
    methods:  GET

participe_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Participe:show" }
    methods:  GET

participe_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Participe:new" }
    methods:  [GET, POST]

participe_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Participe:edit" }
    methods:  [GET, POST]

participe_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Participe:delete" }
    methods:  DELETE
