plainte_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Plainte:index" }
    methods:  GET

plainte_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Plainte:show" }
    methods:  GET

plainte_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Plainte:new" }
    methods:  [GET, POST]

plainte_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Plainte:edit" }
    methods:  [GET, POST]

plainte_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Plainte:delete" }
    methods:  DELETE
