reglement_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Reglement:index" }
    methods:  GET

reglement_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Reglement:show" }
    methods:  GET

reglement_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Reglement:new" }
    methods:  [GET, POST]

reglement_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Reglement:edit" }
    methods:  [GET, POST]

reglement_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Reglement:delete" }
    methods:  DELETE
