tournois_index:
    path:     /
    defaults: { _controller: "NanoFifaBundle:Tournois:index" }
    methods:  GET

tournois_show:
    path:     /{id}/show
    defaults: { _controller: "NanoFifaBundle:Tournois:show" }
    methods:  GET

tournois_new:
    path:     /new
    defaults: { _controller: "NanoFifaBundle:Tournois:new" }
    methods:  [GET, POST]

tournois_edit:
    path:     /{id}/edit
    defaults: { _controller: "NanoFifaBundle:Tournois:edit" }
    methods:  [GET, POST]

tournois_delete:
    path:     /{id}/delete
    defaults: { _controller: "NanoFifaBundle:Tournois:delete" }
    methods:  DELETE
