nano_fifa_actualite:
    resource: "@NanoFifaBundle/Resources/config/routing/actualite.yml"
    prefix:   /actualite


#src/Nano/FifaBundle/Ressources/config/routing.yml

nanofifa_homepage:
    path:     /
    defaults: { _controller: NanoFifaBundle:Actualite:index }

