nanofifa:
    resource: "@NanoFifaBundle/Resources/config/routing.yml"
    prefix:   /

nanofifa_admin:
    resource: "@NanoFifaBundle/Resources/config/admin_routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"