NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"


#les routes de la page d'aministration
nanofifa_admin:
    resource: "@NanoFifaBundle/Resources/config/admin_routing.yml"
    prefix:   /api/admin

#les routes de la page du simple user
nanofifa_user:
    resource: "@NanoFifaBundle/Resources/config/user_routing.yml"
    prefix:   /api


