<?php

namespace nano\fifaBundle\Repository;

/**
 * ChampionatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionatRepository extends \Doctrine\ORM\EntityRepository
{
}
