<?php

namespace Nano\FifaBundle\Repository;

/**
 * Discussion_tournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Discussion_tournoiRepository extends \Doctrine\ORM\EntityRepository
{
}
