<?php

namespace nano\fifaBundle\Repository;

/**
 * Discussion_tounoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Discussion_tounoisRepository extends \Doctrine\ORM\EntityRepository
{
}
