<?php

namespace Nano\FifaBundle\Repository;

/**
 * Discussion_matchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Discussion_matchRepository extends \Doctrine\ORM\EntityRepository
{
}
