<?php

namespace Nano\FifaBundle\Repository;

/**
 * historique_creditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_creditRepository extends \Doctrine\ORM\EntityRepository
{
}
