<?php

namespace nano\fifaBundle\Repository;

/**
 * HistoriqueCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
