<?php

namespace Nano\FifaBundle\Repository;

/**
 * LigueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigueRepository extends \Doctrine\ORM\EntityRepository
{
}
