<?php

namespace nano\fifaBundle\Repository;

/**
 * Match_exhibitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Match_exhibitionRepository extends \Doctrine\ORM\EntityRepository
{
}
