<?php

namespace Nano\FifaBundle\Repository;

/**
 * Match_tounoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Match_tounoisRepository extends \Doctrine\ORM\EntityRepository
{
}
