<?php

namespace Nano\FifaBundle\Repository;

/**
 * PlainteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlainteRepository extends \Doctrine\ORM\EntityRepository
{
}
