<?php

namespace nano\fifaBundle\Repository;

/**
 * plainteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plainteRepository extends \Doctrine\ORM\EntityRepository
{
}
