<?php

namespace Nano\FifaBundle\Repository;

/**
 * PointChampionatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointChampionatRepository extends \Doctrine\ORM\EntityRepository
{
}
