<?php

namespace nano\fifaBundle\Repository;

/**
 * Point_ligueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Point_ligueRepository extends \Doctrine\ORM\EntityRepository
{
}
