<?php

namespace Nano\FifaBundle\Repository;

/**
 * PointLigueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointLigueRepository extends \Doctrine\ORM\EntityRepository
{
}
