<?php

namespace nano\fifaBundle\Repository;

/**
 * Pont_championatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pont_championatRepository extends \Doctrine\ORM\EntityRepository
{
}
