<?php

namespace nano\fifaBundle\Repository;

/**
 * TchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TchatRepository extends \Doctrine\ORM\EntityRepository
{
}
