<?php

namespace Nano\FifaBundle\Repository;

/**
 * TournoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoisRepository extends \Doctrine\ORM\EntityRepository
{
}
