nano\fifaBundle\Entity\Championat:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\ChampionatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
