nano\fifaBundle\Entity\Charge:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\ChargeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        recompense1:
            type: string
            length: 255
        recompense2:
            type: string
            length: 255
        recompense3:
            type: string
            length: 255
    lifecycleCallbacks: {  }
