nano\fifaBundle\Entity\Discussion_tounois:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\Discussion_tounoisRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
