nano\fifaBundle\Entity\HistoriqueCredit:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\HistoriqueCreditRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        somme:
            type: integer
            nullable: true
        date:
            type: datetime
            nullable: true
        details:
            type: string
            length: '560'
            nullable: true
        type:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
