nano\fifaBundle\Entity\Match_exhibition:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\Match_exhibitionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lieu:
            type: string
            length: 255
    lifecycleCallbacks: {  }
