nano\fifaBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
        date:
            type: datetime
    lifecycleCallbacks: {  }
