nano\fifaBundle\Entity\Point_ligue:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\Point_ligueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbrePoints:
            type: integer
            column: nbre_points
    lifecycleCallbacks: {  }
