nano\fifaBundle\Entity\Pont_championat:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\Pont_championatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbrePoints:
            type: integer
            column: nbre_points
    lifecycleCallbacks: {  }
