nano\fifaBundle\Entity\Tchat:
    type: entity
    table: null
    repositoryClass: nano\fifaBundle\Repository\TchatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
            nullable: true
        date:
            type: datetime
    lifecycleCallbacks: {  }
